### ISSUE TITLE
Why support only deb-based systems?

### ISSUE THREAD

**Issue by p7u** [iancleary/ansible-role-zsh_antibody#5]
Tried to use this role on fedora. Guess what the result is...

**Comment by iancleary** [comment]
Hi @p7u, I've only supported deb based systems because that's what I've used personally. This project was an investigation into how I can better share what I've learned creating https://github.com/iancleary/ansible-desktop.  Please notice that also only supports Deb based systems.

> Open to help/contributions, but I actively use Debian based systems because those are what are available at work for my desktop.  I'm interested in Fedora, but frankly don't have experience with it, so I've never thought to support it.

That said, I think with Jeff Geerling's Dockerfiles, the change should be fairly straight forward.

**Comment by iancleary** [comment]
@p7u `v0.3.0` has been imported to https://galaxy.ansible.com/iancleary/zsh_antibody with Fedora 31 and 32 support! 🎉

**Comment by p7u** [comment]
nice! thanks @iancleary
